services:
  app:
    container_name: app-test
    image: app-test
    build: .
    env_file: .env-test
    networks:
      - testnetwork
    ports:
      - 8080:8090
    depends_on:
      - db
    command: pytest -s -v

  db:
    image: postgres:14
    container_name: db
    env_file: .env-test
    volumes:
      - db_vol_data_test:/var/lib/postgresql/data
    networks:
      - testnetwork
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d booking -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3

  redis:
    image: redis
    container_name: redis
    env_file: .env
    networks:
      - mynetwork
    ports:
      - 6379:6379


  celery_worker:
    build: 
      context: .
    container_name: celery_worker
    env_file: .env
    networks:
      - mynetwork
    command: celery -A src.tasks.celery_app:celery_instance worker -l INFO

  celery_beat:
    build: 
      context: .
    container_name: celery_beat
    env_file: .env
    networks:
      - mynetwork
    command: celery -A src.tasks.celery_app:celery_instance beat -l INFO


volumes:
  db_vol_data:
    name: db_vol_data

networks:
  mynetwork:
    name: mynetwork