name: CI/CD pipeline
#run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t konstantinkonov/app:latest .
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push the Docker Image
        run: docker push konstantinkonov/app:latest
  
  lint-format:
    name: Lint and Format
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Pull the Docker image
        run: docker pull app:latest
      - name: Run Ruff check
        run: |
          docker network create myNetwork  
          docker run --rm --network myNetwork konstantinkonov/app ruff check
